parameters:
    session_encryption_secret: '%env(SESSION_ENCRYPTION_SECRET)%'

framework:
    secret: '%env(APP_SECRET)%'  # مفتاح سري لتوقيع الكوكيز وإلغاء تشفيرها

    # تعريف متحكم الأخطاء الخاص بالتطبيق
    error_controller: App\Controller\Error\ErrorController::index

   
    session:
        save_path: '%kernel.project_dir%/var/sessions'
        gc_probability: 100
        gc_divisor: 100
        gc_maxlifetime: 3600
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto 
        cookie_httponly: true 
        cookie_lifetime: 3600
        
    # الحماية من الهجمات csrf مفعلة بشكل افتراضي، يمكن تعطيلها هنا
    csrf_protection: true

    # ملاحظة: الجلسة ستبدأ فقط إذا تمت قراءتها أو كتابتها
    # esi: true
    # fragments: true

# إعدادات تطبيق الاختبار
when@test:
    framework:
        test: true
        session:
            # استخدام تخزين محاكاة للجلسة أثناء الاختبارات
            storage_factory_id: session.storage.factory.mock_file
