controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# config/routes.yaml


private_asset:
    path: /private/{filename}
    controller: App\Controller\PrivateAssetController::index

